apiVersion: v1
kind: Service
metadata: 
  name: app-service
  labels:
    app: myapp-service
    type: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30003
  selector:
      app: myapp-pod
      type: frontend
        
      
